<?php

use Drupal\entity_browser\Entity\EntityBrowser;

/**
 * Implements hook_install().
 */
function lightning_media_image_install() {
  /** @var \Drupal\entity_browser\EntityBrowserInterface $browser */
  $browser = EntityBrowser::load('media_browser');

  $browser->addWidget([
    'settings' => [
      'entity_type' => 'media',
      'bundle' => 'image',
    ],
    'weight' => -9,
    'label' => t('Upload Image'),
    'id' => 'entity_form',
  ]);
  $browser->save();
}
