<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_inline_entity_form_entity_form_alter().
 */
function lightning_media_document_inline_entity_form_entity_form_alter(&$entity_form, FormStateInterface $form_state) {
  if ($entity_form['#entity_type'] == 'media' && $entity_form['#bundle'] == 'document') {
    \Drupal::service('lightning_media.preview.file_upload')->alterForm($entity_form, $form_state, $entity_form['#entity']);
  }
}
