<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function lightning_media_document_form_media_document_form_alter(array &$form, FormStateInterface $form_state) {
  \Drupal::service('lightning_media.preview.file_upload')->alterForm($form, $form_state);
}

/**
 * Implements hook_inline_entity_form_entity_form_alter().
 */
function lightning_media_document_inline_entity_form_entity_form_alter(&$entity_form, FormStateInterface $form_state) {
  if ($entity_form['#entity_type'] == 'media' && $entity_form['#bundle'] == 'document') {
    \Drupal::service('lightning_media.preview.file_upload')->alterForm($entity_form, $form_state, $entity_form['#entity']);
  }
}
