<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function lightning_media_video_form_media_video_form_alter(array &$form, FormStateInterface $form_state) {
  \Drupal::service('lightning_media.preview.embed_code')->alterForm($form, $form_state);
}

/**
 * Implements hook_entity_extra_field_info().
 */
function lightning_media_video_entity_extra_field_info() {
  return \Drupal::service('lightning_media.preview.embed_code')->extraFields('video');
}
